version: '3.8'

services:
  app:
    container_name: api_bridgestone
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8185:8185"
    volumes:
      - .:/code
    # environment:
    #   - ENV_VAR=your_value
