from sqlalchemy import Column, Date, Integer, String, DateTime, Float, Boolean
from ...database import Base


class ItemFaturamento(Base):
    __tablename__ = "hanasync_faturamento_notas"

    # sync_updated_at = Column(DateTime)
    # sync_created_at = Column(DateTime)
    ID = Column(String, primary_key=True, index=True)
    CFOP = Column(String)
    NATUREZA_OPERACAO = Column(String)
    CANCELADA = Column(String)
    RESULTADO_FATURAMENTO = Column(String)
    DOCTYP = Column(String)
    DOC_FAT = Column(String)
    NF_SERVICO = Column(String)
    DOCNUM = Column(Integer)
    NUMERO_NOTA = Column(String)
    OV = Column(Integer)
    OV_MAE = Column(Integer)
    DATA_CRIADA_OV = Column(Date)
    DATA_CRIADA = Column(Date)
    SERIE = Column(String)
    CENTRO = Column(String)
    CLIENTE_ID = Column(String)
    CLIENTE_NOME = Column(String)
    CLASSIFICACAO = Column(String, default="")
    SEGMENTO = Column(String, default="")
    FAMILIA = Column(String, default="")
    GRUPO = Column(String, default="")
    CODIGO_MATERIAL = Column(String)
    COD_FAB = Column(String, default="")
    DESC_MATERIAL = Column(String)
    CONDICAO_PAG = Column(String)
    COND_DESCRICAO = Column(String)
    FORMA_PAGAMENTO = Column(String)
    PAG_FORMA_DESC = Column(String)
    MEIO_PAGTO = Column(String)
    MEIO_PAGTO_DESC = Column(String)
    VLR_UNITARIO = Column(Float, name="VLR.UNITARIO")
    QUANTIDADE = Column(Float)
    TOTAL = Column(Float)
    TOTAL_SEMDESCONTO_SEMJUROS = Column(Float)
    TOTAL_COM_DESCONTO = Column(Float)
    TOTAL_COM_DESCONTO_ITEM = Column(Float)
    TOTAL_DEVIDO = Column(Float)
    DESCONTO_REAL = Column(Float)
    DESCONTO_REAL_PERCENT = Column(Float, name="DESCONTO_REAL%")
    CUSTO_SAP_TOTAL = Column(Float)
    CUSTO_SAP_ITEM = Column(Float)
    LUCRO_SAP_ITEM = Column(Float)
    MARGEM_SAP = Column(Float, name="MARGEM SAP")
    ICMS_ST = Column(Float)
    DESCONTO_ABSOLUTO = Column(Float)
    DESCONTO_ABSOLUTO_PERCENT = Column(String, name="DESCONTO_ABSOLUTO%")
    TOTAL_BRUTO = Column(Float)
    TOTALNF = Column(Float)
    UNIDADE = Column(String)
    ESTADO = Column(String)
    CIDADE = Column(String)
    VENDEDOR_TIPO = Column(String)
    VENDEDOR_ID = Column(Integer)
    VENDEDOR = Column(String)
    MECANICOZ4 = Column(String)
    MECANICOZ5 = Column(String)
    MECANICOZ6 = Column(String)
    MECANICOZ7 = Column(String)
    MECANICOZ8 = Column(String)
    PLACA = Column(String)
    KM = Column(String)
    CREDAT = Column(String)
    OV_TIPO = Column(String)
    BP_TIPO = Column(String)
    CRIADO_POR = Column(String)
    PRECO_VAREJO = Column(Float)
    PRECO_ATACADO = Column(Float)
    JUROS_CONDICAO = Column(Float)
    TIPO_ORDEM = Column(String)
    COMISSAO_TIPO = Column(String)
    COMISSAO_PORCENTAGEM = Column(Float)
    ITEM = Column(String)
    COLETADOR = Column(String)
    MOTIVO_ORDEM = Column(String)
    CENTRO_REG = Column(String)
    COLETADOR_NOME = Column(String)
    COLETADOR_NOME_COMPLETO = Column(String)
    GRUPO_MERC = Column(String)
    GRUPO_MERC_DESC = Column(String)
    SEGMENTO_PRINCIPAL_BP = Column(String)
    REGIAO_AGRO_BP = Column(String)
    # TIMESTAMP_ATUALIZACAO = Column(String)
    VENDEDOR_OV_MAE_ID = Column(Integer)
    VENDEDOR_OV_MAE_NOME = Column(String)
    TIPO_COMISSAO = Column(String)
    AJUSTES_COMISSAO = Column(String)
    PORCENTAGEM_COMISSAO_VENDEDOR = Column(Float)
    PORCENTAGEM_COMISSAO_COLETADOR = Column(Float)
    VALOR_BASE_COMISSAO = Column(Float)
    HORA_CRIADA = Column(String)
    

class Materiais(Base):
    __tablename__ = "hanasync_faturamento_materiais"

    ID = Column(String, primary_key=True, index=True)
    CODIGO_MATERIAL = Column(String)
    COD_FAB = Column(String)
    DESC_MATERIAL = Column(String)
    CLASSIFICACAO = Column(String)
    SEGMENTO = Column(String)
    FAMILIA = Column(String)
    GRUPO = Column(String)
    GRUPO_MERC = Column(String)
    GRUPO_MERC_DESC = Column(String)
    UNIDADE = Column(String)
    ESTADO = Column(String)
    CIDADE = Column(String)
    VENDEDOR_TIPO = Column(String)
    VENDEDOR_ID = Column(Integer)
    VENDEDOR = Column(String)
    MECANICOZ4 = Column(String)
    MECANICOZ5 = Column(String)
    MECANICOZ6 = Column(String)
    MECANICOZ7 = Column(String)
    MECANICOZ8 = Column(String)
    PLACA = Column(String)
    KM = Column(String)
    CREDAT = Column(String)
    OV_TIPO = Column(String)
    BP_TIPO = Column(String)
    CRIADO_POR = Column(String)
    PRECO_VAREJO = Column(Float)
    PRECO_ATACADO = Column(Float)
    JUROS_CONDICAO = Column(Float)
    TIPO_ORDEM = Column(String)
    COMISSAO_TIPO = Column(String)
    COMISSAO_PORCENTAGEM = Column(Float)
    ITEM = Column(String)
    COLETADOR = Column(String)
    MOTIVO_ORDEM = Column(String)
    CENTRO_REG = Column(String)
    COLETADOR_NOME = Column(String)
    COLETADOR_NOME_COMPLETO = Column(String)
    SEGMENTO_PRINCIPAL_BP = Column(String)
    REGIAO_AGRO_BP = Column(String)
    VENDEDOR_OV_MAE_ID = Column(Integer)
    VENDEDOR_OV_MAE_NOME = Column(String)
    TIPO_COMISSAO = Column(String)
    AJUSTES_COMISSAO = Column(String)
    PORCENTAGEM_COMISSAO_VENDEDOR = Column(Float)
    PORCENTAGEM_COMISSAO_COLETADOR = Column(Float)
    VALOR_BASE_COMISSAO = Column(Float)
    HORA_CRIADA = Column(String)
    

class MateriaisNovo(Base):
    __tablename__ = "hanasync_materiais"
    ID = Column(Integer, primary_key=True, index=True)
    COD_SAP = Column(String)
    BARCODE = Column(String)


class Envios(Base):
    __tablename__ = "scanntech_envios"

    id = Column(Integer, primary_key=True, index=True)
    enviado = Column(Boolean, default=False)
    conteudo = Column(String)
    id_lote = Column(String)
    data_envio = Column(Date)
    lista_notas = Column(String)
    devolucao_cancelamento = Column(Boolean, default=False)
