from sqlalchemy import Column, Integer, String, DateTime, Boolean, Float
from sqlalchemy.orm import column_property

from ...database import Base

class Cliente(Base):
    __tablename__ = 'hanasync_clientes'

    # sync_updated_at = Column(DateTime)
    # sync_created_at = Column(DateTime)
    IDCLIENTE = column_property(None)
    ID = Column(String, primary_key=True)
    NOME = Column(String)
    PF_PJ = Column(String, name='PF/PJ')
    CPF_CNPJ = Column(String, name='CPF/CNPJ')
    DOMICILIO = Column(String)
    CONTAGEM = Column(Integer)
    IE = Column(String)
    IM = Column(String)
    # CFOP = Column(String)
    # CONTRIBUINTE_ICMS = Column(Boolean)
    # TERMO_PESQUISA1 = Column(String)
    # TERMO_PESQUISA2 = Column(String)
    # CRIADO_POR = Column(String)
    # DATA_CRIADO = Column(DateTime)
    # MOD_POR = Column(String)
    # MOD_DATA = Column(DateTime)
    # MOD_HORA = Column(String)
    # MOEDA = Column(String)
    # REMESSA = Column(String)
    # FORN_COMP = Column(String)
    # SUJ_IMPOSTO = Column(Boolean)
    # CONCILIACAO = Column(String)
    # TESOURARIA = Column(String)
    # COD_JUROS = Column(String)
    # CREDITO_VAL = Column(Float)
    CIDADE = Column(String)
    CEP = Column(String)
    RUA = Column(String)
    NUMERO = Column(String)
    TELEFONE1 = Column(String)
    COMP_SMS_TELEFONE1 = Column(String)
    OBS_TELEFONE1 = Column(String)
    TELEFONE2 = Column(String)
    COMP_SMS_TELEFONE2 = Column(String)
    OBS_TELEFONE2 = Column(String)
    TELEFONE3 = Column(String)
    COMP_SMS_TELEFONE3 = Column(String)
    OBS_TELEFONE3 = Column(String)
    TELEFONE4 = Column(String)
    COMP_SMS_TELEFONE4 = Column(String)
    OBS_TELEFONE4 = Column(String)
    TELEFONE5 = Column(String)
    COMP_SMS_TELEFONE5 = Column(String)
    OBS_TELEFONE5 = Column(String)
    EMAIL1 = Column(String)
    OBS_EMAIL1 = Column(String)
    EMAIL2 = Column(String)
    OBS_EMAIL2 = Column(String)
    EMAIL3 = Column(String)
    OBS_EMAIL3 = Column(String)
    EMAIL4 = Column(String)
    OBS_EMAIL4 = Column(String)
    EMAIL5 = Column(String)
    OBS_EMAIL5 = Column(String)
    EMAIL6 = Column(String)
    OBS_EMAIL6 = Column(String)
    # F_CLIENTE = Column(Boolean)
    # F_CLIENTE_CONT = Column(Boolean)
    # F_FORNECEDOR = Column(Boolean)
    # F_FORNECEDOR_CONT = Column(Boolean)
    # F_CREDITO = Column(Boolean)
    VAREJO_ATACADO = Column(String)
    # VENDEDOR_Z1_ID = Column(Integer)
    # VENDEDOR_Z1 = Column(String)
    # VENDEDOR_Z1_SOBRENOME = Column(String)
    # VENDEDOR_Z2_ID = Column(Integer)
    # VENDEDOR_Z2 = Column(String)
    # VENDEDOR_Z2_SOBRENOME = Column(String)
    # VENDEDOR_Z3_ID = Column(Integer)
    # VENDEDOR_Z3 = Column(String)
    # VENDEDOR_Z3_SOBRENOME = Column(String)
    # ULTIMA_COMPRA = Column(DateTime)
    # VENDEDOR_FIDELIZADO_TIPO = Column(String)
    # VENDEDOR_FIDELIZADO_ID = Column(Integer)
    # VENDEDOR_FIDELIZADO_NOME = Column(String)
    # VENDEDOR_FIDELIZADO_NOME_ABREV = Column(String)
    # DESCONTO_RECAPAGEM = Column(Float)
    # STATUS_NEGATIVACAO = Column(Boolean)
    # STATUS_PROTESTO = Column(Boolean)
    # STATUS_JURIDICO = Column(Boolean)
    # GRUPO_COOPERATIVA = Column(String)
    # VALOR_ADIANTAMENTO_CLIENTE = Column(Float)
    # UC_VENDEDOR_ID = Column(Integer)
    # UC_VENDEDOR_NOME = Column(String)
    # FAT_12_MESES = Column(Float)
    # MAIOR_FAT_12_MESES = Column(Float)
    # ULTIMO_PAGAMENTO = Column(DateTime)
    # DATA_ULTIMO_PAGAMENTO = Column(DateTime)
    # AMPLIADO_CLIENTE_0100 = Column(String)
    # AMPLIADO_CLIENTE_0200 = Column(String)
    # AMPLIADO_CLIENTE_0300 = Column(String)
    # RECAPAGEM_EMITENOTA = Column(Boolean)
    # REQUISICAO = Column(String)
    SEGMENTO_PRINCIPAL = Column(String)
    REGIAO_AGRO = Column(String)
    # CREDITO = Column(Float)
    # COMPROMISSO_CREDITO = Column(Float)
    # ESGOTAMENTO_CREDITO = Column(Float)
    # CREDITO_DISPONIVEL = Column(Float)
    # HORA_CRIADO = Column(String)
    # STATUS_PERDA = Column(Boolean)
    # STATUS_BLOQUEIO_SEGMENTO_CREDITO = Column(Boolean)
    UF = Column(String)
    # CONDICOES_ESPECIAIS = Column(String)
    # DUPLICATA = Column(String)
    
    